vi117/scrap-yard

frontend/info, frontend/src/App.tsx, frontend/src/Component/Document.tsx, frontend/src/Component/Search.tsx, frontend/src/Component/export.tsx, frontend/src/Model/Document.ts, frontend/src/Model/FsManager.ts, frontend/src/Model/RPCError.ts, frontend/src/Model/RPCManager.ts, frontend/src/Model/chunk.ts, frontend/src/Model/mod.ts, frontend/src/Model/serverInfo.test.ts, frontend/src/Model/serverInfo.ts, frontend/src/Model/share.ts, frontend/src/ViewModel/chunklist.ts, frontend/src/ViewModel/doc.ts
이제부터 `Promise<IRPCMessageManager>`를 리턴합니다. `ServerInfo`를 읽어서 값을 얻어냅니다.
=> fix: RPCManager is now Singleton.

backend/src/router/util.ts, backend/src/rpc.ts, backend/src/server.ts, frontend/jest.config.ts, frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/Component/dirTree.tsx, frontend/src/Model/FsManager.ts, frontend/src/Model/RPCManager.ts, pnpm-lock.yaml, pnpm-workspace.yaml
`FsManager`를 사용하고 있지 않는 오류를 고침
=> fix: DirTree use FsManagerInstance

backend/testworkspace/test2.syd, frontend/package.json, frontend/src/Component/Document.tsx, frontend/src/Component/dirTree.tsx, frontend/src/Model/FsManager.ts, frontend/src/Page/Story/UI.tsx, frontend/src/ViewModel/doc.ts, frontend/src/util/util.ts, pnpm-lock.yaml
FileTree 의 항목을 클릭하면 해당하는 문서가 열림.
=> feat: open with path

frontend/src/Model/RPCManager.ts, frontend/src/ViewModel/IDisposable.ts, frontend/src/ViewModel/doc.ts
frontend에서의 해제하지 않은 이벤트 핸들러로 인한 누수 해결.
=> fix: resource leak

frontend/src/Component/Chunk.tsx, frontend/src/Component/Stash.tsx, frontend/src/ViewModel/chunklist.ts, frontend/src/ViewModel/doc.ts
=> fix: broken stash(close #75)

backend/src/rpc/share.test.ts, backend/src/rpc/share.ts, backend/src/server.test.ts, frontend/src/Model/share.ts, model/src/share.ts
share의 api를 약간 바꾸었다. token을 같이 리턴한다.
테스트도 같이 추가했다.
=> fix: share method

backend/src/rpc/share.ts, frontend/src/Model/share.ts
share 메소드에 대한 문서를 추가했다.
shareGetInfo가 권한 체크하도록 고쳤다.
=> doc: share method

backend/app.ts, backend/import_map.json, backend/src/auth/session.ts, backend/src/config.ts, backend/src/fileServe.ts, backend/src/infoHandle.ts, backend/src/router/handler.ts, backend/src/router/methodHandle.test.ts, backend/src/router/methodHandle.ts, backend/src/router/mod.ts, backend/src/router/responseBuilder.ts, backend/src/router/static.ts, backend/src/router/util.ts, backend/src/rpc.ts, backend/src/rpc/docStore.ts, backend/src/server.ts, backend/src/util.ts, backend/testworkspace/config.jsonc, frontend/src/Model/FsManager.ts, frontend/src/Model/RPCManager.ts, frontend/src/Model/login.ts, frontend/src/Model/mod.ts, frontend/src/Model/serverInfo.ts, frontend/src/ViewModel/chunklist.ts, model/src/error.ts
로그인 기능을 구현하였다.
로그인 기능은 password 아니면 token으로 로그인을 할 수 있다.
fetch할때 `credentials: "include"` 를 포함하는 것을 잊지 않고 해야 cookie가 같이 보내진다.
=> feat: Login

backend/src/router/methodHandle.ts, backend/src/router/responseBuilder.ts, frontend/src/Model/FsManager.ts
=> fix: CORS Allowed Method

backend/src/watcher/fswatcher.test.ts, backend/src/watcher/fswatcher.ts, backend/src/watcher/readWriter.ts, backend/src/watcher/util.test.ts, backend/src/watcher/util.ts
이제 rename을 이용해서 문서를 원자적으로 (POSIX에서는 확실하게) 저장합니다.
=> feat: atomically save document

frontend/src/Component/Chunk.tsx, frontend/src/Component/ShareButton.tsx, frontend/src/Page/Login.tsx, frontend/src/Page/TokenLogin.tsx
=> Add share options

frontend/src/Model/login.ts
코드에서 credentials가 누락되었습니다. 적용한 패치입니다.
=> fix: add credentials

backend/src/rpc/doc.ts, frontend/src/ViewModel/doc.ts
이제 Tag를 수정하면 다른 사용자에게도 전파됩니다. 그리고 그 태그 내용도 문서에 저장됩니다.
=> feat: Tag update

frontend/src/Page/UI.tsx
이제 보고 있는 파일이 바뀌면 타이틀도 바뀝니다. 그리고 일부 `Button`을 `IconButton`으로 바꿨습니다.
=> feat: filename title

backend/src/fileServe.ts, frontend/src/Model/FsManager.ts
`FsManager`에 `rename` 메소드가 추가되었습니다. 이제 파일의 이름을 바꿀 수 있습니다.
=> feat: add rename method

frontend/src/Component/Stash.tsx
z index 오류를 고쳤습니다. stash 위에 Type 이라는 글자가 아래로 가도록 바꾸었습니다.
=> fix: invalid Z index

frontend/src/Model/FsManager.ts
=> fix: add missing method (#119)

frontend/src/App.tsx, frontend/src/Model/RPCManager.ts, frontend/src/Model/login.ts, frontend/src/Model/serverInfo.ts, frontend/src/Page/Login.tsx, frontend/src/Page/Page.tsx, frontend/src/Page/UI.tsx, frontend/src/util/util.ts
접속할때 서버 info를 확인하고 기본적인 정보를 불러옵니다.
login할때 returnTo 를 searchParam으로 사용할 수 있습니다. 로그인이 성공하면 returnTo를 주소로 app을 붙여서 이동합니다.
logout할 때 연결된 Websocket도 같이 끊습니다.
=> feat: login and logout

backend/src/fileServe.ts
=> feat: hide dot file

backend/src/watcher/readWriter.ts
말그대로 임시파일은 이제부터 현재 작업 디렉토리에서 생성됨.
=> fix: temp file is now created in cwd

backend/app.ts, backend/deno.json, backend/src/config.ts, backend/src/infoHandle.ts, backend/src/router/responseBuilder.ts, backend/src/server.ts, backend/src/watcher/fswatcher.ts, backend/testworkspace/.scrap-yard/session.json, frontend/package.json, frontend/src/App.tsx, frontend/src/Component/Divider.tsx, frontend/src/Component/ShareButton.tsx
배포 준비.
static file serve로 파일 배포 준비 중.
=> feat: ready Deploy

frontend/src/App.css, frontend/src/App.tsx, frontend/src/Component/Chunk.tsx, frontend/src/Component/Document.tsx, frontend/src/Component/FileDialog.tsx, frontend/src/Component/FileTree.tsx, frontend/src/Component/Link.tsx, frontend/src/Component/ReadonlyChunk.tsx, frontend/src/Component/Renderer/KatexRenderer.tsx, frontend/src/Component/Settings.tsx, frontend/src/Page/Login.tsx, frontend/src/Page/Page.tsx, frontend/src/Page/UI.tsx
close #25 
단순한 테마가 구현되었습니다. 현재 light과 dark가 구현되었습니다.
=> feat: impl Theme

.dockerignore, DOCKERFILE, frontend/package.json
=> feat: dockerfile
